fxbox/app

- .travis.yml
- README.md
- gulpfile.js
- package.json
- tests/.jshintrc
- tests/common/login_test.js
- tests/foxbox-simulator/http-server.js
- tests/foxbox-simulator/static/login.html
- tests/lib/app.js
- tests/lib/views/accessors.js
- tests/lib/views/login/accessors.js
- tests/lib/views/login/view.js
- tests/lib/views/services/accessors.js
- tests/lib/views/services/view.js
- tests/lib/views/view.js
> Create first (simple) end-to-end and integration tests

- tests/common/logout_test.js
- tests/lib/views/login/view.js
- tests/lib/views/services/view.js
Just a very easy test to start with
> testing logout

- app/index.html
- app/js/lib/foxbox-settings.js
- app/js/lib/foxbox.js
- app/js/views/service.jsx
- app/js/views/services-list-item.jsx
- app/js/views/services-list.jsx
- app/js/views/services/camera.jsx
- app/js/views/services/default.jsx
r? @gmarty If something is not critical I can fix it in the follow ups :)
> Use Taxonomy based Service API. r=gmarty

- app/js/lib/foxbox.js
- app/js/views/themes-new.jsx
Faking the data used by the recipe views.
> Getting ready for demo time

- .babelrc
- app/js/views/navigation-menu.jsx
- app/js/views/services-list-item.jsx
- app/js/views/services.jsx
- app/js/views/services/camera.jsx
- app/js/views/services/default.jsx
- app/js/views/tag-item.jsx
- app/js/views/tag-list.jsx
- app/js/views/themes-new.jsx
- app/js/views/themes.jsx
- app/js/views/user-login.jsx
- app/js/views/user-logout-button.jsx
- gulpfile.js
- package.json
Make sure to:
```bash
$ rm -rf node_modules/
$ npm install
```
> Update the build system to the latest version

- LICENSE
- README.md
- package.json
I found out we didn't have a direct link to travis. I copied the badges from fxfox/foxbox. The coverage one is missing because coverage will require more investigation. 
r? @gmarty
> Add badges and license

- app/css/views/themes.css
- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/recipes.js
- app/js/views/themes-list-item.jsx
- app/js/views/themes-new.jsx
- app/js/views/themes.jsx
@azasypkin: This patch is a bit messy with a lot of code duplication and saving a rule to the box doesn't seem to work.
But if you agree, let's get it landed first and we can fix and refactor it. It's already big.
> Add a class for the recipes. r=azasypkin

- app/js/lib/foxbox/foxbox.js
- app/js/views/services/camera.jsx
- gulpfile.js
- karma.conf.js
- package.json
- tests/unit/test-main.js
- tests/unit/views/services/camera_test.js
Depends on https://github.com/fxbox/foxbox/pull/296 and https://github.com/fxbox/app/pull/39 and https://github.com/fxbox/app/pull/43
>  Update foxbox and camera service view to be compatible with the latest taxonomy (fixes #40). r=gmarty

- app/js/lib/foxbox/db.js
- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/network.js
- app/js/lib/foxbox/recipes.js
@azasypkin: Do you have time for a quick review?
> Prevent extensibility and enforce properties privacy in foxbox lib. r=azasypkin

- app/js/lib/foxbox/recipes.js
This patch contains:
* User friendly name for the IP camera
* Filter out the console adapter
> Minor changes in the recipes

- .eslintrc
- app/css/views/services/default.css
- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/settings.js
- app/js/views/service.jsx
- app/js/views/services-list-item.jsx
- app/js/views/services-list.jsx
- app/js/views/services/camera.jsx
- app/js/views/services/light.jsx
- app/js/views/tag-item.jsx
This patch:
* Add partial support for the Philips Hue adapter (getting values is not done yet)
* Relax the use of eslint `comma-dangle` in preparation of https://github.com/fxbox/app/issues/47
* Fix minor issue in `foxbox.js` (better warning when no boxes are found and only poll the box when the user is logged in)
* Remove the code related to the deprecated service states
> Add support for the Philips Hue adapter. r=azasypkin

- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/network.js
- app/js/lib/foxbox/settings.js
- app/js/views/user-login.jsx
This needs to land around the same time as https://github.com/fxbox/registration_server/pull/18
> Change the discovery to use a fingerprint DNS resolvable name rather than an IP address

- app/hookSW.js
> Webpush click and notificating via postMessage

- app/js/lib/foxbox/foxbox.js
- tests/lib/app.js
> Unregister service worker on foxbox.clear(). r=francisco

- app/js/lib/foxbox/foxbox.js
> Do not ping to <origin>/null/ping if reg server ping fails. r=azasypkin

- app/js/views/user-login.jsx
The current UX spec is located at https://drive.google.com/a/mozilla.com/folderview?id=0B6jZCAHNVaWEdzNIWXhteHM2MUE.
> Change the wording on the login according to the spec.

- .eslintrc
- app/js/app.js
- app/js/lib/foxbox/db.js
- app/js/lib/foxbox/event-dispatcher.js
- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/network.js
- app/js/lib/foxbox/recipes.js
- app/js/lib/foxbox/services/base.js
- app/js/lib/foxbox/services/door-lock.js
- app/js/lib/foxbox/webpush.js
- app/js/views/modal.jsx
- app/js/views/navigation-menu.jsx
- app/js/views/services-list-item.jsx
- app/js/views/services-list.jsx
- app/js/views/services/camera.jsx
- app/js/views/themes-new.jsx
- tests/common/login_test.js
- tests/common/logout_test.js
- tests/common/new_recipe_test.js
- tests/foxbox-simulator/http-server.js
- tests/lib/app.js
- tests/lib/views/accessors.js
- tests/lib/views/login/view.js
- tests/lib/views/recipes/view.js
- tests/lib/views/services/view.js
- tests/unit/controllers/service_test.js
This pull request makes eslint to enforce more coding style. The following new rules are set:
* valid-jsdoc
* eqeqeq
* no-case-declarations
* no-else-return
* no-extra-bind
* no-implicit-coercion
* no-multi-spaces
* no-throw-literal
* no-warning-comments
* arrow-body-style
* arrow-spacing
* object-shorthand
* prefer-const
* prefer-template
No [stylistic rules](http://eslint.org/docs/rules/#stylistic-issues) have been added in this patch. They'll be considered in the future.
> Enforce more coding styles with eslint. r=@azasypkin

- gulpfile.js
> Gulp: Make sure we tear down servers and simulators

- app/js/lib/foxbox/foxbox.js
> Only force the configuration when there is one box discovered. r=azasypkin

- app/hookSW.js
> Rolling back to notifications with png icon since svg icon was not working on linux r=gmarty

- app/js/lib/foxbox/foxbox.js
- app/js/lib/foxbox/settings.js
- app/js/views/user-login.jsx
- tests/registration-server-simulator/http-server.js
- tests/unit/lib/foxbox/foxbox_test.js
- tests/unit/views/user-login_test.js
Fix the multibox login page that was broken for some reason.
> Fix the login page UI. r=azasypkin

- README.md
- assets/badge.svg
- esdoc.json
- gulpfile.js
- package.json
> Make doc a gulp task and add a badge on README. r=azasypkin

- CONTRIBUTING.md
This is a first stab at a page about contribution.
@azasypkin: What do you think?
> Add a CONTRIBUTING file. r=azasypkin
